### ISSUE TITLE
Could you do this [REQUEST]

### ISSUE THREAD

**Issue by pistachit** [kangoka/tiktok-autoviews#6]
Together with pages like vipto.de and homedecoratione.com (old fbsub.de) you could make another script that contains the option of likes and also views, so it could be used on all 3 pages at the same time and everything would be even easier. However, I congratulate you on your work, it has helped me a lot. Keep it up!!!.

Take care

**Comment by kangoka** [comment]
@pistachit @olpexxx As you wished https://github.com/kangoka/tiktodv3
